### ISSUE TITLE
ошибка Cannot find module 'lowdb'

### ISSUE THREAD

**Issue by Darkinggq** [lineage2js/lineage2js#1]
OC линукс дебиан 10
версия node js 12.13.0

я сегодня скачал клон репо из гитхабе сервер л2 хроник с1 из node js

хотел проверить запуск тест логин сервер + игровой сервер собщение ошибка странно

логин сервер
> xxxx@xxxxx-pc:~/lineage-2-node.js-emulator-server$ /home/xxxxxxx/Documents/nodejs/node-v12.13.0-linux-x64/bin/node loginserver.js 
> internal/modules/cjs/loader.js:797
>     throw err;
>     ^
> 
> Error: Cannot find module 'lowdb'
> Require stack:
> - /home/xxxxxxx/lineage-2-node.js-emulator-server/loginserver.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
>     at Module.require (internal/modules/cjs/loader.js:849:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/home/xxxxxxx/lineage-2-node.js-emulator-server/loginserver.js:9:11)
>     at Module._compile (internal/modules/cjs/loader.js:956:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
>     at Module.load (internal/modules/cjs/loader.js:812:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/home/xxxxxxx/lineage-2-node.js-emulator-server/loginserver.js' ]
> }

игровой сервер
> xxxx@xxxxx-pc:~/lineage-2-node.js-emulator-server$ /home/xxxxxxx/Documents/nodejs/node-v12.13.0-linux-x64/bin/node gameserver.js 
> internal/modules/cjs/loader.js:797
>     throw err;
>     ^
> 
> Error: Cannot find module './LogoutOK.js'
> Require stack:
> - /home/xxxxxxx/lineage-2-node.js-emulator-server/gameserver/serverpackets/serverPackets.js
> - /home/xxxxxxx/lineage-2-node.js-emulator-server/gameserver.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
>     at Module.require (internal/modules/cjs/loader.js:849:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/home/xxxxxxx/lineage-2-node.js-emulator-server/gameserver/serverpackets/serverPackets.js:11:16)
>     at Module._compile (internal/modules/cjs/loader.js:956:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
>     at Module.load (internal/modules/cjs/loader.js:812:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>     at Module.require (internal/modules/cjs/loader.js:849:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/xxxxxxx/lineage-2-node.js-emulator-server/gameserver/serverpackets/serverPackets.js',
>     '/home/xxxxxxx/lineage-2-node.js-emulator-server/gameserver.js'
>   ]
> }

@space2pacman 'lowdb', 'LogoutOK.js' эти где брать ?? файл там нету

**Comment by space2pacman** [comment]
Надо установить модуль lowdb
npm install lowdb

Файл LogoutOk.js есть и буква "k" должна быть в нижнем регистре.

Ошибка в gameserver/serverpackets/serverPackets.js
var LogoutOK = require("./LogoutOK.js");

Надо
var LogoutOK = require("./LogoutOk.js");

**Comment by Darkinggq** [comment]
логин сервер
уже установил модуль lowdb
логин работает

игровой сервер
файл старые "LogoutOk.js" изменил "LogoutOK.js"
теперь все работает

![image](https://user-images.githubusercontent.com/17591539/68608885-0e1be900-04c5-11ea-810f-42d24be38d4f.png)


но клиент л2 хроник с1 не запустит линукс вайне собшение ошибка печально (я скачал клиент с1 ссылка https://l2c1x1.com/public/Download.html)
![image](https://user-images.githubusercontent.com/17591539/68608615-6bfc0100-04c4-11ea-86f6-6414a78ee2ce.png)
@space2pacman даеш клиент System мне? архив System для л2 с1

не давно вайне тест клиент л2 классик запустил но сервер старые версию только для клиент с1 :)
![image](https://user-images.githubusercontent.com/17591539/68608793-d01ec500-04c4-11ea-9ea5-868452faf842.png)

**Comment by Darkinggq** [comment]
сейчас попробуем скачать 
![image](https://user-images.githubusercontent.com/17591539/68609235-d1042680-04c5-11ea-94ad-345f887c9dab.png) 
винд10 через эмулятор вайне для линукс

**Comment by Darkinggq** [comment]
изменил System ссылка выше скрин `System For Win10` линукс вайне не запустит л2 с1 System/L2.exe устарел очень давности

линукс вайне
л2 с4 не тестил
л2 интерлюд не тестил

л2 классик работает
новые хроник тоже работает

**Comment by ilyafuu** [comment]
л2 интерлюд чистые клиент запускает работает

**Comment by Darkinggq** [comment]
линукс вайне л2 интерлюд чистые  запуск клиент работает
![image](https://user-images.githubusercontent.com/17591539/68612514-bf268180-04cd-11ea-9f1d-b0c861bd6f97.png)

прог L2 FileEdit `l2.ini` оргинал адрес официально  `ServerAddr=L2authd.Lineage2.com` изменил адрес 127.0.0.1 сохранил файл запуск клиент ошибка странно

![image](https://user-images.githubusercontent.com/17591539/68612302-49bab100-04cd-11ea-8484-aedb4985b10e.png)

`l2.ini` зашифрован проблем прог  L2 FileEdit не понятно для вайне -_-

неизвестно проблем L2 FileEdit или вайне ша поишу другие прог L2 FileEdit работает или нет

**Comment by Darkinggq** [comment]
FileEdit другие программа тоже ошибка выше скрин `Files are....` бесполезно
 даеш мне l2.ini для с1 ? адрес 127.0.0.1 )

**Comment by space2pacman** [comment]
> логин сервер
> уже установил модуль lowdb
> логин работает
> 
> игровой сервер
> файл старые "LogoutOk.js" изменил "LogoutOK.js"
> теперь все работает
> 
> ![image](https://user-images.githubusercontent.com/17591539/68608885-0e1be900-04c5-11ea-810f-42d24be38d4f.png)
> 
> но клиент л2 хроник с1 не запустит линукс вайне собшение ошибка печально (я скачал клиент с1 ссылка https://l2c1x1.com/public/Download.html)
> ![image](https://user-images.githubusercontent.com/17591539/68608615-6bfc0100-04c4-11ea-86f6-6414a78ee2ce.png)
> @space2pacman даеш клиент System мне? архив System для л2 с1
> 
> не давно вайне тест клиент л2 классик запустил но сервер старые версию только для клиент с1 :)
> ![image](https://user-images.githubusercontent.com/17591539/68608793-d01ec500-04c4-11ea-9ea5-868452faf842.png)

1) Смена протокола не поможет так как пакеты, которые посылают клиенты серверу отличаются между хрониками. 

2) Попробуйте этот файл l2.ini - https://yadi.sk/d/r157f1v7nP2ksg

3) Для декодирования/кодирования файла используйте эту программу - https://yadi.sk/d/TgnxUYSo41qL0A
