### ISSUE TITLE
Cannot Load Game

### ISSUE THREAD

**Issue by melikadze** [lineage2js/lineage2js#2]
After properly installing everything. trying to connect my server in Logs socket sees that I'm connected to the server but the client does not change screen to character creation or login into the actual world.

I'm using username pacman and password pacman.
![image](https://user-images.githubusercontent.com/40162641/94343081-b7f55d00-0026-11eb-82f1-0793250002f6.png)

**Comment by space2pacman** [comment]
all accounts
{
  "accounts": [
    {
      "login": "a",
      "password": "a",
      "accessLevel": 0
    },
    {
      "login": "b",
      "password": "b",
      "accessLevel": 0
    },
    {
      "login": "c",
      "password": "c",
      "accessLevel": 0
    },
    {
      "login": "d",
      "password": "d",
      "accessLevel": 0
    },
    {
      "login": "e",
      "password": "e",
      "accessLevel": 0
    },
    {
      "login": "pacman",
      "password": "pacman",
      "accessLevel": -1
    }
  ],
  
account pacman have access level -1
Please use account: a:a, b:b, c:c, d:d, e:e or change access level on account pacman

**Comment by melikadze** [comment]
thanks for response buddy,
I already dig in that database file and tried other accounts such as username: a password: a result is the same.
![image](https://user-images.githubusercontent.com/40162641/94360987-38b56700-00c2-11eb-9800-27ea2a6bb300.png)

**Comment by space2pacman** [comment]
Try downloading client or patch for Windows 10 from here

https://l2c1x1.com/public/Download.html

**Comment by melikadze** [comment]
I have their client and patch, but still can't go to any further screen such as server select or character creation.

**Comment by space2pacman** [comment]
This week I will try to upload my client on Google disk and a detailed guide on how to connect.

**Comment by space2pacman** [comment]
You edited file l2.ini?

**Comment by space2pacman** [comment]
Show me screenshot gameserver window

**Comment by space2pacman** [comment]
Try this file l2.ini
https://drive.google.com/file/d/1_BMSJbVSamfFtGcd73ieP8ICo_rpjaNS/view?usp=sharing
IP in ini file: 127.0.0.1

**Comment by melikadze** [comment]
Be in touch man. I will test everything from fresh. as I know l2c1x1 using pure c1 client but a modified system and you can edit c1 l2.ini  with L2FileEdit and save as c4 protocol 212 version and it works.

**Comment by space2pacman** [comment]
Let me know if you can connect using the new file l2.ini

**Comment by space2pacman** [comment]
Has your problem been resolved?

**Comment by space2pacman** [comment]
Please give me feedback

**Comment by LeonanCarvalho** [comment]
Hello inside the L2j Version 0.4.1 you will find util called `updateIni.bat`, you can use that to edit .ini with your IP, in other way using c4 system may work, but will not be the pure c1 client =)
[l2j-dist-0.4.1.zip](https://github.com/lineage2js/lineage2js/files/5470924/l2j-dist-0.4.1.zip)
